#!/bin/bash
# Author: Imaran Afzal

cd /home
for DIR in *
do
	CHK=$(grep -c "/home/$Dir" /etc/passwd)
	if [ $CHK -ge 1 ]
	then
		echo "$DIR is assigned to a user"
	else
		echo "$DIR is NOT assigned to a user"
	fi
done
