#!/bin/bash

nmcli d wifi rescan

bssid=$(nmcli device wifi list | sed -n '1!p' | cut -b 9- | dmenu -p "Select WiFi:" -l 10 | cut -d' ' -f1)

pass=$(echo | dmenu -p "Enter password:" | sed 's/ //g')

nmcli device wifi connect $bssid password $pass

